---
- hosts: 172.31.85.192
  become: yes
  tasks:
  - name:
    command: hostname -f
    register: myresults

  - name: i want to see result
    debug:
      msg: "{{myresults}}"
  - name: install git
    apt:
      name: git
      state: present
    when: myresults.stderr == "" 
  - name: install tree
    apt:
      name: tree
      state: present
    when: myresults.stderr !== ""         