---
- hosts: mywebservers
  become: yes
  tasks:
  - name: install webserver on ubuntu nodes
    apt:
     name: "{{mywebpackonubuntu}}"
     state: present
    when: ansible_os_family == "Debian"

 
  - name: i want to start webserver on ubuntu nodes
    service:
      name: "{{mywebpackonubuntu}}"
      state: started
    when: ansible_os_family == "Debian"  