---
- hosts: 172.31.85.192
  become: yes
  tasks:
  - import_tasks: myimport.yml
  - name: create a folder
    file:
      path: /home/ubuntu/myfolder
      state: directory
  - name: copy a files
    copy:
      src: mycopyfile    
      dest: /home/ubuntu/mycopyfile.txt
  - name: install apache2
    apt:
      name: apache2
      state: present

  - name: create a dynamic file
    template:
       src: myjinja.j2
       dest: /var/www/html/index.html    

  - name: download remote files
    get_url:
       url:  https://get.jenkins.io/war-stable/2.361.1/jenkins.war   
       dest: /home/ubuntu/
       force_basic_auth: yes